### ISSUE TITLE
이슈 테스트

### ISSUE THREAD

**Issue by sahwasa** [whangsy/test1#1]
초대 없이 이슈 작성 가능 확인
----------------

**Comment by whangsy** [comment]
네. 감사합니다.
![image](https://github.com/whangsy/test1/assets/20316861/bb605963-8d0c-46d7-986b-41dacb03105e)

**Comment by kitkit2023** [comment]
![image](https://github.com/whangsy/test1/assets/147117095/e1fa23de-fbb3-46f6-8422-a6d37ce15992)
단말기 LCD화면 → 방송이력 → 로그 확인 시 시간란에 날짜(월,일) 표기가 되지 않음

**Comment by whangsy** [comment]
댓글을 달라는건 참여하는 사람들 글쓰기 가능한지 댓들을 달라는 의미였고,
문제가 있는건 각각 한건씩 이슈를 달아주세요.
