### ISSUE TITLE
민방위 실제, 시험, 훈련 구분에 따른 관리이력 표출 문구

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#10]
- 민방위 통보문 발송 시 민방위 통보구분에 따른 Actual(실제), Exercise(훈련) 까지는 정상적으로 표출되지만 test 구분자는 시험이 아닌 test로 표출됨
 : 방송이력 및 관리이력에 표출되는 문구를 설명
![image](https://github.com/whangsy/test1/assets/147117095/5d71b892-b1c4-46fc-8bc3-f454a6e0a955)
![image](https://github.com/whangsy/test1/assets/147117095/9220f2fe-5ee0-4496-8d03-d9d0337bebfc)

**Comment by whangsy** [comment]
테스트는 의미 없습니다.
