### ISSUE TITLE
단말기 네트워크 변경 시 정상 연결

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#12]
네트워크 관리 환경설정 →1.경보장치 네트워크설정
단말기 LCD화면에서 IP변경 가능하나,
단말기 IP변경시 단말기 화면에서 통신오류라고 표출된 후 5초 정도뒤에 다시 연결됨으로 화면표출
![KakaoTalk_20231012_180506895](https://github.com/whangsy/test1/assets/147117095/46366931-0310-4775-9a07-4cffaabf4a58)

**Comment by whangsy** [comment]
서버에서 ip check 기능을 꺼놨습니다. 단말기는 문제없습니다.
