### ISSUE TITLE
시스템상태 - 케이블 연결상태 이상

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#14]
- 통보문 수신 및 훈련방송 시 간헐적으로 하단에 오디오,  스피커 등 전부 연결상태(1)로 표출
 : 시간이 지나면 자동으로 돌아옴
![image](https://github.com/whangsy/test1/assets/147117095/bbf44efa-d4cb-4317-bafd-cfe49789bd58)
(이상상태)
![image](https://github.com/whangsy/test1/assets/147117095/30753e71-d43a-4c22-b214-1b94e50317ac)
(정상상태)

**Comment by whangsy** [comment]
정상입니다. 오디오 출력 중 일 때 1로 설정됩니다.
