### ISSUE TITLE
지진경보 설정(거리) 이슈

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#15]
지진1단계 설정을 위 사진과 같이 설정(거리 100km 이상) 후 거리 100km이상인 통보문 발송 시 방송송출이 안됨
![KakaoTalk_20231017_114530982](https://github.com/whangsy/test1/assets/147117095/27b68b48-ca00-42fd-a063-bfa80142adcb)

**Comment by whangsy** [comment]
이상, 이내에 대한 부분은 반영이 안되어 있습니다. 이게 수정되어야 하는지 육수석님과 협의해보세요.

**Comment by whangsy** [comment]
육수석님과 이내로 고정하는걸로 협의했습니다.
