### ISSUE TITLE
6.관리자메뉴 내 문구 수정 

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#16]
행정업무를 업무로 수정 부탁드립니다 
![{78658FAE-A695-4FDE-B41E-7A494FD79477} png](https://github.com/whangsy/test1/assets/147117095/9ab0fa0b-183d-4977-aa31-7e7f81624e16)

**Comment by whangsy** [comment]
수정했습니다.

**Comment by kitkit2023** [comment]
![image](https://github.com/whangsy/test1/assets/147117095/7d90e280-9773-4826-9474-c644e0107bde)
어제 수정됨을 확인 하였으나, 현재 다시 행정업무로 확인됩니다 수정 부탁드립니다
