### ISSUE TITLE
메뉴 선택 시 두군데가 동시에 표시됨 

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#17]
예시) 기관경보 메뉴 사용 중 현장경보 메뉴로 이동 시, 현재 사용 중인 메뉴인 기관경보 색상이 옅어지고 마우스 커서를 올려놓은(진입 대상인) 현장경보가 진한 파란색으로 표시되어야 하나, 반대로 표시되는 이슈가 있었습니다.
간헐적으로 발생 가능한 오류인지 확인 요청드립니다.
![image](https://github.com/whangsy/test1/assets/147117095/c8fa36fe-a3e1-4df7-9c6d-621945af0184)

![{1BBDAF62-0F86-43D0-9D40-F77B483FFC4E} png](https://github.com/whangsy/test1/assets/147117095/6870bb11-fb87-48f3-a8ac-06f21aa6b5aa)

**Comment by whangsy** [comment]
재현이 되지 않습니다.
