### ISSUE TITLE
제품특징 확인 및 현행화 부탁드립니다 

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#18]
![image](https://github.com/whangsy/test1/assets/147117095/a1a2063b-085f-4551-801a-a9deaad8f2dd)

티케이랩스에서 작성한 제품특징 부분 확인 및 소프트웨어 부분 현행화 부탁드립니다
----------------------------------------------------------------------------------------------

- Embedded Linux 기반을 통한 기능추가 및 확장 가능
- 각각의 프로그램 스레드마다 감시를 통해 장애(에러)발생 대처 가능
- 안정성 확보를 위한 WatchDog(복구기능) 지원
- 멀티캐스팅 지원(다중접속)
- RTC 내장, 시간 오류 시 직접설정 및 NTP 동기화 설정 가능
- GNSS GPS 내장으로 시간 및 위치정보의 업데이트 가능
- USB 메모리 또는 또는 Micro SD Card를 통한 용량 확장 가능
- USB를 이용한 장비에서 손쉬운 업그레이드 가능 
- Http프로토콜로 S/W 받아서 원격 업그레이드 가능(Port 9640)
- 원격지에서 네트워크로 장비 상태감시 가능
- TFT LCD 터치 패널 사용으로 직관적으로 조작 가능
- 내부 스피커 및 외부 오디오 출력을 가지고 있으며 , 실제 앰프 방송 출력 여부 모니터링이 가능
- 통신장애 발생시 자동 재 접속 기능 내장
- UPS내장으로 외부 전원 차단 시 배터리 전원으로 동작 가능
- 지상파 UHD재난경보 서비스를 위한 UHD재난방송 수신

**Comment by whangsy** [comment]
삭제
* 각각의 프로그램 스레드마다 감시를 통해 장애(에러)발생 대처 가능
* USB 메모리 또는 또는 Micro SD Card를 통한 용량 확장 가능
* Http프로토콜로 S/W 받아서 원격 업그레이드 가능(Port 9640)

추가
* 기상청 재난 경보 수신 및 경보 발령
* 민방위 경보 수신 및 경보 발령
* 자동 S/W download 및 update 가능
