### ISSUE TITLE
UHD수신 상태 표시

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#19]
![image](https://github.com/whangsy/test1/assets/147117095/22a32169-8b57-415f-b06e-c7e31a2ba546)
![image](https://github.com/whangsy/test1/assets/147117095/a884998e-8a9f-49eb-b19c-e9480cc72c37)
중계서버 오프라인일때 UHD수신 상태 표시가 중계서버 접속 성공 시의 화면과 같습니다 확인 부탁드립니다

**Comment by whangsy** [comment]
중계서버랑 UHD는 상관이 없습니다.
