### ISSUE TITLE
URL오류

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#26]
![Inked{9831BE7E-80B2-4EAB-BC81-F084740AA529} png_LI](https://github.com/whangsy/test1/assets/147117095/6beab365-f45b-4b5d-b5de-75f67eccddc4)

단말기 lcd 주소(https://122.199.200.204:8443/lcd/main)로 들어왔을 때 관리자 페이지로 연결됩니다

**Comment by whangsy** [comment]
정상입니다.
