### ISSUE TITLE
UHD수신관리 메뉴 내 오류

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#27]
![{B4FE3A3F-06B9-449E-A242-1E93097B4DBE} png](https://github.com/whangsy/test1/assets/147117095/ca016392-cb96-4e00-934e-d2d2948e466b)
UHD수신관리 자연재난 부분 재난종류에 지진이 두개 추가로 확인됩니다

![{00C2C32A-7CC4-4702-9619-6392979AD22B} png](https://github.com/whangsy/test1/assets/147117095/0a6c6c40-254b-4bc0-aa50-645a322d1fc1)
이와 같이 수정부탁드립니다

**Comment by whangsy** [comment]
지진속보와 지진조기경보인데 다온에서는 하나로 합쳐놨네요. 3개로 분리해서 표시하겠습니다.
