### ISSUE TITLE
방송이력 메뉴 수정 

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#28]
![image](https://github.com/whangsy/test1/assets/147117095/e40d5821-d3d5-4e28-8906-2a9474a828b9)

방송이력 부분에 메세지는 UHD재난 경보방송이라고 확인되는데, 경보부분은 [지진]TEST라고 확인됩니다 
확인 부탁드립니다

**Comment by whangsy** [comment]
무슨 말인지 명확하게 기술해주세요.
