### ISSUE TITLE
방송이력 메뉴 수정

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#29]
![11111](https://github.com/whangsy/test1/assets/147117095/6ab77828-242e-4a19-840f-d8bb95594b78)

![{17CB69D3-4C2B-4D00-AC4C-B07BC61FD68B} png](https://github.com/whangsy/test1/assets/147117095/800551d4-b9ee-4951-a50b-386821d47689)

방송이력 부분에 메세지는 UHD재난 경보방송이라고 확인되고, 경보부분은 [지진]TEST라고 확인되는데
이 부분이 관리이력에서 보이는 것 처럼 UHD재난 경보방송 경보수신이라고 수정 요청드립니다

**Comment by whangsy** [comment]
다온에서는 어떻게 나오나요 ?

**Comment by kitkit2023** [comment]
> 다온에서는 어떻게 나오나요 ?

새로 작성했습니다 확인 부탁드립니다
