### ISSUE TITLE
방송이력 메뉴 

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#30]
![image](https://github.com/whangsy/test1/assets/147117095/99911415-4b26-4b08-a543-70bd4c7c3b5a)
다온에서는 경보메뉴와 메세지메뉴가 없고 수신시각,방송시각과 로그내용만 확인됩니다

**Comment by whangsy** [comment]
uhd는 앞에 uhd를 붙이도록 수정했습니다. 메세지는 방송메세지가 아니라 description 정보를 표기하도록 수정하였습니다.
