### ISSUE TITLE
Lcd화면 수정 요청 

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#32]
중계서버 접속 오류일 시에 처음에는 1번 화면이 표출되었다가 몇 초 이후에는 IP가 나와있는 2번 화면으로 표출됩니다
수정 부탁드립니다
![InkedKakaoTalk_20231019_172027445_LI](https://github.com/whangsy/test1/assets/147117095/b71c4ea8-aec2-4eee-9a0f-04540b17496f)

![InkedKakaoTalk_20231019_172028290_LI](https://github.com/whangsy/test1/assets/147117095/c7ffc143-7b4d-4953-a2dd-b22a1797c65b)

**Comment by whangsy** [comment]
수정완료

**Comment by kitkit2023** [comment]
> 수정완료

방금 확인했는데 수정이 안되었습니다 
![KakaoTalk_20231020_091819340](https://github.com/whangsy/test1/assets/147117095/029b5ebe-34a1-4ac3-a590-90912d5c81cf)
