### ISSUE TITLE
지진정보(해역) 테스트

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#5]
- 단말기 설정
: 1단계 지역 3 ~ 4 / 해역 3.5 ~ 4.5 / 거리 10km이내

-내용
 : 단말기 방송송출 조건에 부합하지 않는 설정으로 지진정보 통보문 발송했을때 지역같은 경우 방송송출이 되지 않지만, 해역은 방송송출이 됨
  → 통보문 규모 3.6 / 거리 100km이상으로 설정
[cap-14.zip](https://github.com/whangsy/test1/files/12837116/cap-14.zip)

  → 지역/해역 설정은 CAP파일 내 seaflag 0(지역) / 1(해역) 으로 설정

**Comment by whangsy** [comment]
수정하였습니다.
