### ISSUE TITLE
경보방송 횟수 적용되지 않음

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#6]
- 경보방송 횟수가 2회로 설정하였으나, 실제 1회 밖에 송출되지 않음
 : UHD 수신관리 설정도 동일
![image](https://github.com/whangsy/test1/assets/147117095/937bd54a-fed9-4ce4-a0c1-b3363a2f95c5)

**Comment by whangsy** [comment]
수정했습니다.
