### ISSUE TITLE
UHD 테스트 통보문 방송송출 설정 확인

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#7]
- UHD수신관리에서 지진 및 테스트방송 체크 해제하였으나 지속적으로 UHD 테스트 방송송출 됨
 : 4분마다 들어오는 UHD 테스트 통보문
![image](https://github.com/whangsy/test1/assets/147117095/828fb530-a460-4534-ba00-0deb8b553148)
![image](https://github.com/whangsy/test1/assets/147117095/797d8af0-3c75-41b4-9aeb-c4c5ff643cc3)

**Comment by whangsy** [comment]
테스트 방송 여부만 끄면 됩니다.
로그 상으로는 계속 수신된걸로 보이는데, 다시 저장을 한 후부터는 나오지 않습니다.
재현이 되는지 봐야하겠습니다.
