### ISSUE TITLE
단말기에 없는 재난 수신 시 중계서버와 순단 발생

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#8]
- CAP파일 내용이 이상하거나, 단말기에 없는 재난종류(지진해일경보 해제, 화산주의보 해제 등) 수신 시  단말기 로그에 통신 오류 표출과 함께 중계서버와 연결이 잠깐 끊어졌다 2~3초뒤에 다시 연결됨
![image](https://github.com/whangsy/test1/assets/147117095/f4c57d18-5a22-41a1-aef9-321cce4f21a6)

**Comment by whangsy** [comment]
![image](https://github.com/whangsy/test1/assets/20316861/95130e64-4fee-4f79-978e-b9f4f596bb44)
행정동코드가 없는 전문입니다.
