### ISSUE TITLE
통보문 수신 시 단말기 LCD 경보화면 일찍꺼짐

### ISSUE THREAD

**Issue by kitkit2023** [whangsy/test1#9]
- 통보문 수신 시 수신 음성과 함께 붉은색 LCD 화면이 표출되는데 음성이 끝나기도 전에 LCD화면이 꺼짐
 : LCD화면은 3초 정도뒤에 꺼지고 음성만 출력

**Comment by whangsy** [comment]
lcd 꺼짐과 음성은 상관이 없습니다.
